src/Cascader.jsx
src/Menus.jsx

feat: support Cascader[dropdownMenuColumnStyle]

---

package.json
src/Cascader.jsx
src/Menus.jsx
tests/index.js
tests/index.spec.js
tests/keyboard.spec.js

close https://github.com/ant-design/ant-design/issues/4411

Keyboard support

---

src/Cascader.jsx

Menus组件没有用到父组件Cascader传递过来的value

Menus组件没有用到父组件Cascader传递过来的value

---

README.md
package.json
src/Cascader.jsx
src/Menus.jsx
tests/demoOptions.js
tests/index.spec.js

close https://github.com/ant-design/ant-design/issues/10896

correct typo: filedNames => fieldNames

---

README.md
assets/index.less
examples/custom-arrow-icon.html
examples/custom-arrow-icon.js
examples/custom-arrow-icon.less
src/Cascader.jsx
src/Menus.jsx
tests/index.spec.js
tests/keyboard.spec.js

see examples/custom-arrow-icon.js
暴露一个接口可以使用svg图标

support expand icon.

---

src/Cascader.jsx

close [ant-design#16763](https://github.com/ant-design/ant-design/issues/16763)

fix: Popup/result list not closing on TabOut #16763

---

src/Cascader.tsx
src/Menus.tsx

https://github.com/ant-design/ant-design/pull/24221

feat: cascader component value support number type

---

package.json
tests/__snapshots__/index.spec.js.snap

chore: Add react and react-dom as peer dependencies and update snapshot

---

README.md
package.json
src/Cascader.tsx
tests/index.spec.tsx

ref https://github.com/ant-design/ant-design/issues/32127

fix: Missing popupClassName

---

src/util.ts
tests/index.spec.tsx

fix https://github.com/ant-design/ant-design/issues/32556

fix: first level number option should show label correct

---

src/Cascader.tsx
src/util.ts
tests/fieldNames.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/32820

fix: Cascader with same label & value makes display issue

---

src/OptionList/Column.tsx
tests/checkable.spec.tsx

Fixes  fix multiple select trigger onclick twice [issue](https://github.com/ant-design/ant-design/issues/33014)

:bug: fix multiple select trigger onclick twice

---

src/Cascader.tsx

export SignleCascaderProps and MultipleCascaderProps for use by antd cascader component ts enhancement
[相关pr](https://github.com/ant-design/ant-design/pull/33188)

export SignleCascaderProps and MultipleCascaderProps

---

src/Cascader.tsx
tsconfig.json

close https://github.com/react-component/cascader/issues/234
﻿

fix: fix cascader onChange type

---

src/OptionList/Column.tsx
src/OptionList/index.tsx
src/OptionList/useKeyboard.ts
tests/index.spec.tsx

fix https://github.com/ant-design/ant-design/issues/33273

fix: Should scroll when activeKey changed

---

src/Cascader.tsx

https://github.com/ant-design/ant-design/issues/33297

fix: resolve antd matchInputWidth invalid

---

examples/debug.tsx
src/OptionList/index.tsx
tests/index.spec.tsx

This reverts commit 6153468e8f057785b8e744d827f4bf8501ac3aba.

Revert "fix: cascader should support double quotes in value and label (#245)"

---

examples/debug.tsx
src/OptionList/index.tsx
tests/index.spec.tsx

- fix: cascader should support double quotes in value and label (#245)
- fix: use common reg

fix: should support quotes in label and value

---

src/OptionList/useKeyboard.ts
tests/keyboard.spec.js

resolve https://github.com/ant-design/ant-design/issues/34329
resolve https://github.com/ant-design/ant-design/issues/34312

fix: search with enter not trigger correct change params

---

src/hooks/useSearchOptions.ts
tests/search.spec.tsx

resolves https://github.com/ant-design/ant-design/issues/34505

fix: crash when exist options with same value on different levels

---

package.json

See https://github.com/ant-design/ant-design/pull/35618 for more details.

chore: bump rc-tree

---

examples/debug.tsx
src/hooks/useDisplayValues.ts
tests/index.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/36941

fix: Disabled option should not be closable

---

examples/hover.tsx
src/OptionList/Column.tsx
tests/checkable.spec.tsx
tests/demoOptions.ts
tests/index.spec.tsx

background: https://github.com/ant-design/ant-design/issues/41134

fix:  fix not hiding the previous level option when there is no sub option

---

.gitignore
package.json
src/hooks/useSearchOptions.ts
tests/search.spec.tsx

master branch 也要个。
fix https://github.com/ant-design/ant-design/issues/41376

fix: changeOnSelect should not show children

---

examples/search.tsx
src/OptionList/CacheContent.tsx
src/OptionList/index.tsx
tests/search.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/41810

chore: memo of OptionList

---

examples/change-on-select.tsx
src/OptionList/Column.tsx
src/OptionList/index.tsx

close https://github.com/ant-design/ant-design/issues/41806

fix: Cascader expandTrigger="hover" behavior when search

---

.gitignore

run build 产生的site dist没有被ignore

chore: add dist site production ignore

---

src/utils/commonUtil.ts
src/utils/treeUtil.ts
tests/checkable.spec.tsx

fix https://github.com/ant-design/ant-design/issues/43870

fix: conduct should skip disabled

---

README.md
src/Cascader.tsx
tests/search.spec.tsx

https://github.com/ant-design/ant-design/discussions/43951

feat: support autoClearSearchValue

---

src/hooks/useSearchOptions.ts
tests/search.spec.tsx

fix https://github.com/ant-design/ant-design/issues/37247
close https://github.com/react-component/cascader/pull/319

fix: Search will make option selectable

---

examples/panel.tsx
examples/search.tsx
src/Panel.tsx
tests/Panel.spec.tsx

Patch Panel `rtl` & `notFoundContent` props.

chore: rtl & empty

---

examples/panel.tsx
src/OptionList/useActive.ts
tests/Panel.spec.tsx

fix https://github.com/ant-design/ant-design/issues/46069
close https://github.com/react-component/cascader/pull/450

fix: control panel not working
