README.md, examples/dynamic-options.js, src/Cascader.jsx, src/Menus.jsx, tests/index.spec.js
```js
<cascade loadData={
function(selectedOptions){
const options = this.state.options;
const targetOption = selectedOptions[selectedOptions.length - 1];
targetOption.label += ' loading';
// 动态加载下级数据
setTimeout(() => {
targetOption.label = targetOption.label.replace(' loading', '');
targetOption.children = [{
'label': targetOption.label + '动态加载1',
'value': 'dynamic1',
}, {
'label': targetOption.label + '动态加载2',
'value': 'dynamic2',
}];
this.setState({options});
}, 1000);
this.setState({options});
}
}>
```
=> fix onSelect

src/Cascader.jsx, src/Menus.jsx
* super() missing props argument.
* unnecessary constructor() without override.
=> fix(props): super() missing props argument.

src/Menus.jsx
=> feat: add className for item which has children, close: #15

src/Cascader.jsx, src/Menus.jsx, tests/index.spec.js
- fix `changeOnSelect` can't work when `expandTrigger='hover'`
- mouseEnter should not trigger value changing(when `expandTrigger='hover'`)
https://github.com/ant-design/ant-design/issues/7480
=> fix changeOnSelect can't work when expandTrigger='hover'

README.md, examples/custom-field-name.html, examples/custom-field-name.js, src/Cascader.jsx, src/Menus.jsx, tests/index.spec.js
Add labelField and valueField for custom label field name and value field name, It is not should just use value and label
=> add labelField and valueField for custom label field name and value field name

src/Cascader.tsx, tests/keyboard.spec.js
This allows the caller to also handle the keys that returned early (eg. Escape) and stopPropagation on them, for example.
=> fix: Call passed onKeyDown in all cases when handling keydown event

src/Menus.tsx, tests/index.spec.js
fix https://github.com/ant-design/ant-design/issues/30659
=> fix: options show when children is empty

src/Cascader.tsx, src/OptionList/Column.tsx, src/OptionList/index.tsx, src/index.tsx, tests/checkable.spec.tsx
close https://github.com/ant-design/ant-design/issues/33302
=> fix: Cascade should not show checkbox when options is empty

src/OptionList/Column.tsx, tests/checkable.spec.tsx
解决了[issue](https://github.com/react-component/cascader/issues/228)的问题
=> fix: multiple mode lose indeterminate except first-level

examples/debug.tsx, src/OptionList/index.tsx, src/utils/commonUtil.ts, tests/index.spec.tsx
原本  children 为 空数组时，上游可以选择是个 bug。但是似乎 bug as feature 特别多。干脆 children 是空数组也当成 leaf 来处理保持一致性。
=> fix: Trade empty children option as leaf node

src/Cascader.tsx, src/OptionList/Column.tsx, tests/search.spec.tsx
close https://github.com/ant-design/ant-design/issues/33671
﻿
=> fix: should trigger onChange if click on options of multiple cascader with searchValue

examples/debug.tsx, src/OptionList/index.tsx, tests/index.spec.tsx
close https://github.com/ant-design/ant-design/issues/33928
=> fix: cascader should support double quotes in value and label

src/index.tsx
#220 忘了在index文件中导出SignleCascaderProps和MultipleCascaderProps了。这边补上。ant-design的[相关pr](https://github.com/ant-design/ant-design/pull/33947)
=> export SignleCascaderProps and MultipleCascaderProps to index file

src/hooks/useSearchOptions.ts, tests/search.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/34062
=> fix: empty children is a leaf node

src/OptionList/Column.tsx, src/OptionList/index.tsx, tests/fieldNames.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/34322
=> fix: Empty should not show value as label

src/Cascader.tsx, src/utils/commonUtil.ts, src/utils/treeUtil.ts, tests/index.spec.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
https://github.com/ant-design/ant-design/issues/34193
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      set `showCheckedStrategy `  to `'parent'\|'child''` for value type       |
| 🇨🇳 Chinese |   设置`showCheckedStrategy `为`'parent'\|'child'`选择返回值方式      |
⚠️ Please check all items below before review. ⚠️
=> feat: add showCheckedStrategy

examples/multiple.tsx, src/Cascader.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
https://github.com/ant-design/ant-design/issues/34193
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add exports type  for `rc-cascader`       |
| 🇨🇳 Chinese |   为`rc-cascader` 添加导出的type      |
⚠️ Please check all items below before review. ⚠️
=> feat: add exports type

src/hooks/useDisplayValues.ts, tests/selector.spec.tsx
fix: https://github.com/ant-design/ant-design/issues/34631
=> fix:  BaseSelect uses `key` property of displayValues as `itemKey`

examples/adjust-overflow.tsx, src/OptionList/useKeyboard.ts, tests/keyboard.spec.tsx
close https://github.com/ant-design/ant-design/issues/43401
=> fix(antd@4.x): Cascader should not clear search input when press left/right key

examples/adjust-overflow.tsx, src/OptionList/useKeyboard.ts, tests/keyboard.spec.tsx
close https://github.com/ant-design/ant-design/issues/43401
=> fix(antd@5.x): Cascader should not clear search input when press left/right key

package.json, tests/__snapshots__/search.spec.tsx.snap
升级 rc-select，移除 showArrow 属性，将 inputIcon 重命名为 suffixIcon
=> chore: bump rc-select

tests/__snapshots__/search.spec.tsx.snap
I am in the process of updating the snapshots to resolve the encountered errors that occur when running npm run test. This resolves [issue #434](https://github.com/react-component/cascader/issues/434)
=> test: update snapshots

package.json
- https://github.com/ant-design/ant-design/pull/46667
=> chore(deps): bump rc-select from 4.10.0 to 4.11.0
